### PR TITLE
[WIP] 0709 meeting notes.

### PR DESCRIPTION
**Pull request by szha**

### CODE REVIEW

**Comment by szha** [comment]
@prasanthpul @harryskim @joohoon @jimspohrer feel free to propose the agenda items for our next meeting here and I will add them to the pull request.

**Comment by prasanthpul** [comment]
there were several items in https://github.com/onnx/steering-committee/blob/master/meeting-notes/20200625.md that we did not get to. do any of them need to carry forward?

**Comment by harryskim** [comment]
Some other items that came up: 
1. Moving SC meeting time to 4pm on Mondays to be accomodate potential participants from China (e.g. Ke Zhang Arch & Infra SIG chair) 
2. SIG co-chair application followup (Ke & Vinitra) 
3. Separating ONNX and optimizer.

**Comment by prasanthpul** [comment]
Since the file serves as both agenda and notes, I merged so the agenda is published for anyone who is looking for it ahead of the mtg. You can continue editing it. BTW - you have merge permissions too.

**Pull request merged**
